[drake_bazel_download] experimental package parameters

diff --git a/drake_bazel_download/.github/ci_build_test b/drake_bazel_download/.github/ci_build_test
--- a/drake_bazel_download/.github/ci_build_test
+++ b/drake_bazel_download/.github/ci_build_test
@@ -3,5 +3,32 @@
 
 set -euxo pipefail
 
+override_repository=0
+
+while [ "${1:-}" != "" ]; do
+  case "$1" in
+    --override-repository)
+      override_repository=1
+      ;;
+    *)
+      echo 'Invalid command line argument' >&2
+      exit 1
+  esac
+  shift
+done
+
+override_repository_flag=()
+if [[ ${override_repository} -eq 1 ]]; then
+  # Use what we installed to $HOME/drake,
+  # rather than the URL to the most recent nightly release
+  # found in drake_bazel_download/MODULE.bazel.
+  override_repository_flag+=("--override_repository=+_repo_rules2+drake=$HOME/drake")
+
+  # Setup $HOME/drake as a Bazel workspace via
+  # BUILD and WORKSPACE files.
+  ln -sf $(realpath drake.BUILD.bazel) "$HOME/drake/BUILD.bazel"
+  touch "$HOME/drake/WORKSPACE.bazel"
+fi
+
 bazel version
-bazel test //...
+bazel test "${override_repository_flag[@]}" //...
diff --git a/drake_bazel_download/setup/install_prereqs b/drake_bazel_download/setup/install_prereqs
--- a/drake_bazel_download/setup/install_prereqs
+++ b/drake_bazel_download/setup/install_prereqs
@@ -31,6 +31,25 @@
 
 set -euxo pipefail
 
+experimental_packaging_url=
+
+while [ "${1:-}" != "" ]; do
+  case "$1" in
+    --experimental-packaging-url)
+      shift
+      if [[ $# -eq 0 ]]; then
+        echo 'No argument specified for --experimental-packaging-url' >&2
+        exit 1
+      fi
+      experimental_packaging_url="$1"
+      ;;
+    *)
+      echo 'Invalid command line argument' >&2
+      exit 1
+  esac
+  shift
+done
+
 maybe_sudo=
 if [[ "${EUID}" -ne 0 ]]; then
   maybe_sudo=sudo
@@ -51,8 +70,9 @@ EOF
 )
 
 # Download the drake source
-wget -O drake.tar.gz \
-  https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-jammy.tar.gz
+drake_url="https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-jammy.tar.gz"
+[[ ! -z "${experimental_packaging_url}" ]] && drake_url="${experimental_packaging_url}"
+wget -O drake.tar.gz ${drake_url}
 trap 'rm -f drake.tar.gz' EXIT
 tar -xf drake.tar.gz -C $HOME
 
