Run GHA jobs on custom builds of Drake (#374)
Adds experimental parameters to drake_cmake_installed, drake_cmake_installed_apt, drake_bazel_download, drake_pip, and drake_poetry, and enables running them from GitHub Actions with experimental versions of Drake packages/wheels.

diff --git a/drake_bazel_download/setup/install_prereqs b/drake_bazel_download/setup/install_prereqs
--- a/drake_bazel_download/setup/install_prereqs
+++ b/drake_bazel_download/setup/install_prereqs
@@ -31,6 +31,25 @@
 
 set -euxo pipefail
 
+package_url=
+
+while [ "${1:-}" != "" ]; do
+  case "$1" in
+    --package-url)
+      shift
+      if [[ $# -eq 0 ]]; then
+        echo 'No argument specified for --package-url' >&2
+        exit 1
+      fi
+      package_url="$1"
+      ;;
+    *)
+      echo 'Invalid command line argument' >&2
+      exit 1
+  esac
+  shift
+done
+
 maybe_sudo=
 if [[ "${EUID}" -ne 0 ]]; then
   maybe_sudo=sudo
@@ -51,8 +70,7 @@ EOF
 )
 
 # Download the drake source
-wget -O drake.tar.gz \
-  https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-jammy.tar.gz
+wget -O drake.tar.gz "${package_url:-https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-jammy.tar.gz}"
 trap 'rm -f drake.tar.gz' EXIT
 tar -xf drake.tar.gz -C $HOME
 
diff --git a/drake_cmake_installed_apt/.github/ubuntu_apt_setup b/drake_cmake_installed_apt/.github/ubuntu_apt_setup
--- a/drake_cmake_installed_apt/.github/ubuntu_apt_setup
+++ b/drake_cmake_installed_apt/.github/ubuntu_apt_setup
@@ -3,19 +3,48 @@
 
 set -euxo pipefail
 
+package_url=
+
+while [ "${1:-}" != "" ]; do
+  case "$1" in
+    --package-url)
+      shift
+      if [[ $# -eq 0 ]]; then
+        echo 'No argument specified for --package-url' >&2
+        exit 1
+      fi
+      package_url="$1"
+      ;;
+    *)
+      echo 'Invalid command line argument' >&2
+      exit 1
+  esac
+  shift
+done
+
 export DEBIAN_FRONTEND=noninteractive
 
 apt-get -qq update || (sleep 30; apt-get -qq update)
 apt-get -o Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy --no-install-recommends \
   install build-essential ca-certificates cmake gnupg lsb-release wget
 
-readonly codename="$(lsb_release -cs)"
+if [[ ! -z "${package_url}" ]]; then
+  # Install a custom Drake package if specified.
+  wget -O drake.deb ${package_url}
+  trap 'rm -f drake.deb' EXIT
 
-wget -qO- --retry-connrefused https://drake-apt.csail.mit.edu/drake.asc \
-  | gpg --dearmor - > /etc/apt/trusted.gpg.d/drake.gpg
-echo "deb [arch=amd64] https://drake-apt.csail.mit.edu/${codename} ${codename} main" \
-  > /etc/apt/sources.list.d/drake.list
+  apt-get -o Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy --no-install-recommends \
+    install ./drake.deb
+else
+  # Otherwise, install the latest released version.
+  readonly codename="$(lsb_release -cs)"
 
-apt-get -qq update || (sleep 30; apt-get -qq update)
-apt-get -o Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy --no-install-recommends \
-  install drake-dev
+  wget -qO- --retry-connrefused https://drake-apt.csail.mit.edu/drake.asc \
+    | gpg --dearmor - > /etc/apt/trusted.gpg.d/drake.gpg
+  echo "deb [arch=amd64] https://drake-apt.csail.mit.edu/${codename} ${codename} main" \
+    > /etc/apt/sources.list.d/drake.list
+
+  apt-get -qq update || (sleep 30; apt-get -qq update)
+  apt-get -o Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy --no-install-recommends \
+    install drake-dev
+fi
