Run Jenkins jobs on custom builds of Drake (#376)
Adds experimental parameters to drake_cmake_external, drake_bazel_external, and drake_bazel_external_legacy, and enables running these examples via Jenkins with Drake PRs.

diff --git a/drake_cmake_external/.github/ci_build_test b/drake_cmake_external/.github/ci_build_test
--- a/drake_cmake_external/.github/ci_build_test
+++ b/drake_cmake_external/.github/ci_build_test
@@ -3,6 +3,25 @@
 
 set -euxo pipefail
 
+drake_commit_hash=
+
+while [ "${1:-}" != "" ]; do
+  case "$1" in
+    --drake-commit-hash)
+      shift
+      if [[ $# -eq 0 ]]; then
+        echo 'No argument specified for --drake-commit-hash' >&2
+        exit 1
+      fi
+      drake_commit_hash="$1"
+      ;;
+    *)
+      echo 'Invalid command line argument' >&2
+      exit 1
+  esac
+  shift
+done
+
 cmake --version
 
 mkdir build
@@ -10,7 +29,14 @@ pushd build
 
 export LD_LIBRARY_PATH="${PWD}/install/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
 
-cmake ..
+cmake_args=()
+if [[ ! -z "${drake_commit_hash}" ]]; then
+  # Use a specific commit of Drake source,
+  # rather than the latest from master.
+  cmake_args+=(-DDRAKE_COMMIT_HASH=${drake_commit_hash})
+fi
+
+cmake .. "${cmake_args[@]}"
 cmake --build .
 
 cd drake_external_examples
@@ -20,4 +46,3 @@ popd
 
 chmod -R a+w build || true
 rm -rf build
-
