[PyPI examples] experimental wheels parameters

diff --git a/drake_pip/setup/install_prereqs b/drake_pip/setup/install_prereqs
--- a/drake_pip/setup/install_prereqs
+++ b/drake_pip/setup/install_prereqs
@@ -3,6 +3,33 @@
 
 set -euxo pipefail
 
+setup_env_args=()
+
+while [ "${1:-}" != "" ]; do
+  case "$1" in
+    --wheel-experimental-url)
+      shift
+      if [[ $# -eq 0 ]]; then
+        echo 'No argument specified for --wheel-experimental-url' >&2
+        exit 1
+      fi
+      setup_env_args=(--wheel-experimental-url $1)
+      ;;
+    --python-version)
+      shift
+      if [[ $# -eq 0 ]]; then
+        echo 'No argument specified for --python-version' >&2
+        exit 1
+      fi
+      setup_env_args+=(--python-version $1)
+      ;;
+    *)
+      echo 'Invalid command line argument' >&2
+      exit 1
+  esac
+  shift
+done
+
 maybe_sudo=
 if [[ "${EUID}" -ne 0 ]]; then
   maybe_sudo=sudo
@@ -22,4 +49,4 @@ ${maybe_sudo} apt-get install --no-install-recommends $(cat <<EOF
 EOF
 )
 
-setup/setup_env
+setup/setup_env "${setup_env_args[@]}"
diff --git a/drake_pip/setup/setup_env b/drake_pip/setup/setup_env
--- a/drake_pip/setup/setup_env
+++ b/drake_pip/setup/setup_env
@@ -3,8 +3,40 @@
 
 set -euxo pipefail
 
-PYTHON_VERSION=${1:-'3'}
-echo "Creating virtual environment with python${PYTHON_VERSION}"
+wheel_experimental_url=
+python_version='3'
 
-"python${PYTHON_VERSION}" -m venv env
-"env/bin/pip$PYTHON_VERSION" install -r requirements.txt
+while [ "${1:-}" != "" ]; do
+  case "$1" in
+    --wheel-experimental-url)
+      shift
+      if [[ $# -eq 0 ]]; then
+        echo 'No argument specified for --wheel-experimental-url' >&2
+        exit 1
+      fi
+      wheel_experimental_url="$1"
+      ;;
+    --python-version)
+      shift
+      if [[ $# -eq 0 ]]; then
+        echo 'No argument specified for --python-version' >&2
+        exit 1
+      fi
+      python_version="$1"
+      ;;
+    *)
+      echo 'Invalid command line argument' >&2
+      exit 1
+  esac
+  shift
+done
+
+echo "Creating virtual environment with python${python_version}"
+"python${python_version}" -m venv env
+# Install from requirements.txt, which currently only includes drake.
+"env/bin/pip$python_version" install -r requirements.txt
+
+# Use experimental wheels if specified, on the respective OS.
+if [[ ! -z "${wheel_experimental_url}" ]]; then
+  "env/bin/pip$python_version" install "${wheel_experimental_url}"
+fi
